const meals = [
  {
    idMeal: "52772",
    strMeal: "Teriyaki Chicken Casserole",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Japanese",
    strInstructions:
      "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
    strTags: "Meat,Casserole",
    strYoutube: "https://www.youtube.com/watch?v=4aZr5hZXP_s",
    strIngredient1: "soy sauce",
    strIngredient2: "water",
    strIngredient3: "brown sugar",
    strIngredient4: "ground ginger",
    strIngredient5: "minced garlic",
    strIngredient6: "cornstarch",
    strIngredient7: "chicken breasts",
    strIngredient8: "stir-fry vegetables",
    strIngredient9: "brown rice",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "3/4 cup",
    strMeasure2: "1/2 cup",
    strMeasure3: "1/4 cup",
    strMeasure4: "1/2 teaspoon",
    strMeasure5: "1/2 teaspoon",
    strMeasure6: "4 Tablespoons",
    strMeasure7: "2",
    strMeasure8: "1 (12 oz.)",
    strMeasure9: "3 cups",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52773",
    strMeal: "Honey Teriyaki Salmon",
    strDrinkAlternate: null,
    strCategory: "Seafood",
    strArea: "Japanese",
    strInstructions:
      "Mix all the ingredients in the Honey Teriyaki Glaze together. Whisk to blend well. Combine the salmon and the Glaze together.\r\n\r\nHeat up a skillet on medium-low heat. Add the oil, Pan-fry the salmon on both sides until it’s completely cooked inside and the glaze thickens.\r\n\r\nGarnish with sesame and serve immediately.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    strTags: "Fish,Breakfast,DateNight",
    strYoutube: "https://www.youtube.com/watch?v=4MpYuaJsvRw",
    strIngredient1: "Salmon",
    strIngredient2: "Olive oil",
    strIngredient3: "Soy Sauce",
    strIngredient4: "Sake",
    strIngredient5: "Sesame Seed",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "1 lb",
    strMeasure2: "1 tablespoon",
    strMeasure3: "2 tablespoons",
    strMeasure4: "2 tablespoons",
    strMeasure5: "4 tablespoons",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52774",
    strMeal: "Pad See Ew",
    strDrinkAlternate: null,
    strCategory: "Chicken",
    strArea: "Thai",
    strInstructions:
      "Mix Sauce in small bowl.\r\nMince garlic into wok with oil. Place over high heat, when hot, add chicken and Chinese broccoli stems, cook until chicken is light golden.\r\nPush to the side of the wok, crack egg in and scramble. Don't worry if it sticks to the bottom of the wok - it will char and which adds authentic flavour.\r\nAdd noodles, Chinese broccoli leaves and sauce. Gently mix together until the noodles are stained dark and leaves are wilted. Serve immediately!",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
    strTags: "Pasta",
    strYoutube: "https://www.youtube.com/watch?v=Ohy1DELF4is",
    strIngredient1: "rice stick noodles",
    strIngredient2: "dark soy sauce",
    strIngredient3: "oyster sauce",
    strIngredient4: "soy sauce",
    strIngredient5: "white vinegar",
    strIngredient6: "sugar",
    strIngredient7: "water",
    strIngredient8: "peanut oil",
    strIngredient9: "garlic",
    strIngredient10: "Chicken",
    strIngredient11: "Egg",
    strIngredient12: "Chinese broccoli",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "6oz/180g",
    strMeasure2: "2 tbsp",
    strMeasure3: "2 tbsp",
    strMeasure4: "2 tsp",
    strMeasure5: "2 tsp",
    strMeasure6: "2 tsp",
    strMeasure7: "2 tbsp",
    strMeasure8: "2 tbsp",
    strMeasure9: "2 cloves",
    strMeasure10: "1 cup",
    strMeasure11: "1",
    strMeasure12: "4 cups",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52775",
    strMeal: "Vegan Lasagna",
    strDrinkAlternate: null,
    strCategory: "Vegan",
    strArea: "Italian",
    strInstructions:
      "1) Preheat oven to 180 degrees celcius. \r\n2) Boil vegetables for 5-7 minutes, until soft. Add lentils and bring to a gentle simmer, adding a stock cube if desired. Continue cooking and stirring until the lentils are soft, which should take about 20 minutes. \r\n3) Blanch spinach leaves for a few minutes in a pan, before removing and setting aside. \r\n4) Top up the pan with water and cook the lasagne sheets. When cooked, drain and set aside.\r\n5) To make the sauce, melt the butter and add the flour, then gradually add the soya milk along with the mustard and the vinegar. Cook and stir until smooth and then assemble the lasagne as desired in a baking dish. \r\n6) Bake in the preheated oven for about 25 minutes.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg",
    strTags: "",
    strYoutube: "https://www.youtube.com/watch?v=VU8cXvlGbvc",
    strIngredient1: "green red lentils",
    strIngredient2: "carrot",
    strIngredient3: "onion",
    strIngredient4: "zucchini",
    strIngredient5: "coriander",
    strIngredient6: "spinach",
    strIngredient7: "lasagne sheets",
    strIngredient8: "vegan butter",
    strIngredient9: "flour",
    strIngredient10: "soya milk",
    strIngredient11: "mustard",
    strIngredient12: "vinegar",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: null,
    strIngredient17: null,
    strIngredient18: null,
    strIngredient19: null,
    strIngredient20: null,
    strMeasure1: "1 cups",
    strMeasure2: "1",
    strMeasure3: "1",
    strMeasure4: "1 small",
    strMeasure5: "sprinking",
    strMeasure6: "150g",
    strMeasure7: "10",
    strMeasure8: "35g",
    strMeasure9: "4 tablespoons",
    strMeasure10: "300ml",
    strMeasure11: "1.5 teaspoons",
    strMeasure12: "1 teaspoon",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: null,
    strMeasure17: null,
    strMeasure18: null,
    strMeasure19: null,
    strMeasure20: null,
    strSource: null,
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export default meals;
